# Generated by Django 3.2.4 on 2021-06-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=35)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
